### ISSUE TITLE
URGENT v 2.2.0 breaks build

### ISSUE THREAD

**Issue by eshellman** [vhf/free-programming-books-lint#15]
It looks like the most recent update breaks the F-P-B build. The linter emits this error for all files:

```
warning  SyntaxError: Invalid regular expression: /(?<!\/)\|/: Invalid group
    at LinkText (/opt/hostedtoolcache/node/6.17.1/x64/lib/node_modules/free-programming-books-lint/node_modules/remark-lint-no-pipes-in-links/index.js:44:21)
```

**Comment by eshellman** [comment]
@computamike @vhf could you fix or revert?

**Comment by vhf** [comment]
Sure, done. I reverted 9d1862b46a18be529c49ab36b5c36ee6f7a6e3d8 and pushed a new version since fpb always pulls the latest : https://github.com/EbookFoundation/free-programming-books/blob/f96e2754aea7a83311a0860e9b24a9e617f1507e/.github/workflows/fpb-lint.yml#L16

**Comment by vhf** [comment]
Now that I think about it, the error could suggest that [node 6](https://github.com/EbookFoundation/free-programming-books/blob/f96e2754aea7a83311a0860e9b24a9e617f1507e/.github/workflows/fpb-lint.yml#L15) is too old for @computamike 's plugin. Node 6 has been deprecated since 2019-04-18. It could be something else, just a thought.
